site_name: 开发知识wiki
site_description: 开发知识wiki
site_author: tink
site_url: https://docs.cyub.vip/dev-wiki
strict: false

nav:
  - 简介: index.md
  - 操作系统: 
    - IO: computer-system/io.md
    - proc文件系统: computer-system/proc.md
    - NPTL: computer-system/nptl.md
    - 容器:
      - 简介: container/install.md
      - 镜像: container/image.md
      - cgroup: container/cgroup.md
      - namespace: container/namespace.md
    - 常用命令: computer-system/command.md
    - Systemtap: computer-system/systemtap.md
    - CPU架构: computer-system/cpu-arch.md
    - 编译Linux内核: computer-system/compiling-linux-kernel.md
  - 计算机网络:
    - TCP: computer-network/tcp/README.md
    - HTTP: computer-network/http/README.md
  - 数据库:
    - mysql:
      - 概览: database/mysql/简介.md
      - 事务: database/mysql/事务.md
      - 索引: database/mysql/索引.md
      - FAQ: database/mysql/FAQ.md
    - Elasticsearch:
      - 概览: database/elasticsearch/README.md
      - 内存占用: database/elasticsearch/memory.md
      - 性能调优: database/elasticsearch/performance_tuning.md
      - 生产配置参考: database/elasticsearch/production_configuring.md
      - docs value与 field data: database/elasticsearch/doc_values_and_fielddata.md
    - Redis: database/redis/redis.md
  - 开发语言:
    - Go: language/Go.md
  - 系统设计:
    - 系统设计: system-design/index.md
    - 缓存系统: cache/README.md
    - 系统设计入门: system-design/system-design-primer/index.md
    - what you should know:
      - Ｃ程序员该知道的内存知识: what-should-you-know/README.md
  - Jupyter:
    - Go-Frameworks-Github-Fork-Stats: jupyter/Go-Frameworks-Github-Fork-Stats.ipynb
    - Pandas完全指南: jupyter/Pandas完全指南.ipynb
    - Spark上手示例:
      - jupyter/Spark上手示例1：RDD操作.ipynb
      - jupyter/Spark上手示例2：DataFrame操作.ipynb
  - 视频:
    - 操作系统: video/os.md
    - 数据结构与算法: video/Data structures.md
    - C/C++: video/c_c++.md
  - QA:
    - redis: qa/redis.md
    - mysql: qa/mysql.md
    - tcp: qa/tcp.md
    - http: qa/http.md
    - 缓存: qa/cache.md
    - nginx: qa/nginx.md
    - 消息队列: qa/queue.md
    - IO: qa/io.md
    - protobuf: qa/protobuf.md
    - go: qa/go.md 
    - 分布式: qa/dist.md
    - Elasticsearch: qa/es.md
    - docker: qa/docker.md
    - 参考资料: qa/ref.md


# Copyright
copyright: Copyright &copy; 2023 - 2024 Tink

# Configuration
theme:
  name: material
  language: 'zh'
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Fira Code
    code: Fira Code
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: iso_date
  - glightbox
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      ignore: ["system-design/*.ipynb"]
  - print-site

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde